### ISSUE TITLE
OsgiResolveRemote as a task Key ?

### ISSUE THREAD

**Issue by reyman** [digimead/sbt-osgi-manager#10]
Hi,

I'm interested to chain multiple operation using `sbt-osgi-manager` and `sbt-osgi` plugin :

```
osgiResolveRemote
compile
dependencyFetch
osgiBundle
```

I'm using sbt project defined in .scala file.

I want to merge in a single result folder 
- the jar fetched by `dependencyFetch` and 
- jar created by sbt-osgi (by osgiBundle) after compile.

I first think to create a custom `TaskKey` like "assemble-project", i found TaskKey for [dependencyFetch](https://github.com/digimead/sbt-dependency-manager/blob/master/src/main/scala/sbt/dependency/manager/Keys.scala) , but it seems `osgiResolveRemote` doesn't exist  in `DmKey` and [Keys](https://github.com/digimead/sbt-osgi-manager/blob/7ff6972df2e4ffab374c508080edcb2bb9af6a2a/src/main/scala/sbt/osgi/manager/Keys.scala) of sbt-osgi-manager  
Is there a way to call `osgiResolveRemote` without using `onLoad` hooks on `Global` (i don't know how to use it with project ... waiting for an answer on stack http://stackoverflow.com/questions/38222935/call-onload-only-when-project-is-loaded-in-sbt-console ) ? 

Thanks for your help,
SR

**Comment by ezh** [comment]
I absolutely misunderstand your build sequence.

Why? So many 
1st you load your project
2nt you add your OSGi dependencies to libraryDependencies (and why osgiResolveRemote? not osgiResolve?)
3rd IMHO you must do `compile`
4th IMHO you must do `package` or `"assemble-project` or something that create jar

Why are you using dependencyFetch in build sequence?
How **jar creation sequence** depends on **dependency resolution onLoad**? It is absolutely different processes.

Why do you want to run osgiResolve each time when you do something? It is absolutely unnecessary.

**Comment by reyman** [comment]
Ok, i'm not clear : 

I compile scala file to make a plugin for "OpenMOLE" which need need P2 osgi jar from `msi.gama.headless` (on P2 internet site of Gama software) to compile + some sbt plugin dependencies from `OpenMOLE` i take in local

```
  val osgiSettings = Seq(
    OsgiKeys.importPackage := Seq("*"),
    OsgiKeys.privatePackage := Seq("!scala.*"),
    OsgiKeys.requireCapability := """osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.7))""",
    OsgiKeys.exportPackage := Seq("org.openmole.plugin.task.gama.*"),
    OsgiKeys.bundleActivator := Some("org.openmole.plugin.task.gama.Activator"),
    resolvers += Resolver.sonatypeRepo("snapshots"),
    unmanagedBase := baseDirectory.value / "./target/deps",
    organization := "org.openmole",
    name := "openmole-gama"
  )

 lazy val core = Project(
      id = "openmole-gama",
      base = file("./org.openmole.plugin.task.gama/")) enablePlugins(SbtOsgi) settings(osgiSettings ++ DependencyManager ++ OSGiManagerWithDebug(): _*) settings( //enablePlugins(SbtOsgi) settings(gamaSettings ++ DependencyManager ++ OSGiManagerWithDebug(): _*) settings(
      name := "task.gama",
      scalaVersion := "2.11.8",
      version := "6.0-SNAPSHOT",
      addCompilerPlugin("org.scalamacros" %% "paradise" % "2.1.0" cross CrossVersion.full),
      DMKey.dependencyFilter in DMConf := Some(sbt.DependencyFilter.fnToModuleFilter{m => m.configurations == Some("osgi")}),

      resolvers in OSGiConf += typeP2("Eclipse Mars p2 update site" at "http://download.eclipse.org/releases/mars/"),
      resolvers in OSGiConf += typeP2("GAMA update site" at "http://vps226121.ovh.net/updates/"),
      libraryDependencies in OSGiConf += typeP2(OSGi.ECLIPSE_PLUGIN % "msi.gama.headless" % OSGi.ANY_VERSION withSources),
      libraryDependencies += "biz.aQute" % "bndlib" % "2.0.0.20130123-133441",
      libraryDependencies +=  "com.google.code.findbugs" % "jsr305" % "2.0.3" % "test",
      libraryDependencies += "org.openmole" %% "org-openmole-core-dsl" % openmoleVersion % "provided",
      libraryDependencies += "org.openmole" %% "org-openmole-plugin-task-external" % openmoleVersion % "provided")
```

 I need to generate an OSGI jar which contain correct compiled file `org.openmole.plugin.task.gama`, but i also need all jar dependencies linked to `msi.gama.headless` to run this jar into openmole software. Perhaps is more clear ? 

1 - I resolve p2 site to obtain msi.gama.headless dependencies
2 - I use this dependencies to compile org.openmole.plugin.task.gama scala file
3 - I run `osgiBundle` to generate the first OSGI jar of OpenMOLE plugin which need `msi.gama.headless` dependencies (in MANIFEST.MF) to run correctly on OpenMole
4 - I download all jar to `/target/deps` folder using `dependencyFetch`
5 - I merge jar from 4 and jar from 3 in a single folder i load in OpenMole :)

I'm new to sbt, so perhaps this way to do that is silly...

**Comment by ezh** [comment]
There are a thousand ways to do right thing. I don't want to judge what is right and what is wrong.
1. You may specify folder for `product` and you may specify folder for fetched dependencies (https://github.com/digimead/sbt-dependency-manager/blob/master/src/main/scala/sbt/dependency/manager/Plugin.scala#L51). This must be the same folder.
2. You may define your own task that `dependsOn` jar generation and DMKey.dependencyTaskFetch

??? Is there any difficulties? I don't think so.

**Comment by ezh** [comment]
Oh I see that you want to invoke osgiResolveRemote only if you run the specific task, but I see no reason for this. What is the reason to skip osgiResolveRemote execution at project loading?

**Comment by reyman** [comment]
Yeah my problem is that `osgiResolveRemote` is not a `TaskKey`, and when i try to use `onLoad hooks on Global` osgiResolveRemote is not recognized because i'm not in project `openmole-gama` which contain the  `DependencyManager ++ OSGiManagerWithDebug()`.

This is the question on stack :  http://stackoverflow.com/questions/38222935/call-onload-only-when-project-is-loaded-in-sbt-console ?

**Comment by ezh** [comment]
I read it.
I have code with a lot of nested projects. Some of them use onLoad hooks and I switch between them with `project blablabla`
I really not understand why don't add onLoad hook to subproject `openmole-gama` ?

**Comment by reyman** [comment]
Ok ! I probably misunderstand the onLoad Hooks 
I'm interested to read some of your project build file to learn that, can you give me a link to some gist or github file which redirect to these hooks definition ?
Thanks a lot

**Comment by reyman** [comment]
Ok, i have the code for Global, nut i'm interested to hook that with project only

```
      onLoad in Global :=  {
        ((s: State) => { "osgiResolveRemote" :: s }) compose (onLoad in Global).value },
```

I continue to be interested to read you project file to learn if it's possible :)

**Comment by ezh** [comment]
About my projects - it is not possible :pensive: 

I learn `onLoad` hook by reading source code of SBT
and use search results like
https://github.com/search?utf8=%E2%9C%93&q=onLoad+extension%3Asbt&type=Code&ref=advsearch&l=&l=
https://github.com/search?utf8=%E2%9C%93&q=onLoad+in+extension%3Ascala&type=Code&ref=searchresults

Also remember that you may resolve dependencies in one project and use reference to them in another project. So you may have distinct project with shared dependencies and subprojects with build configuration like this:
https://github.com/digimead/sbt-osgi-manager/blob/master/src/sbt-test/osgi-manager/subproject/build.sbt#L25

Also you may mix Build.scala and build.sbt. Add onLoad hook to local/per project build.sbt

A lot of ways... There may be more... Spend your own lifetime to find solution :smile:

Of course I'll be happy to merge your pull request if you rewrite `OsgiResolve(Remote)` as a task.
