### ISSUE TITLE
Bundles with embedded dependecies: Compilation fails

### ISSUE THREAD

**Issue by kenwenzel** [digimead/sbt-osgi-manager#4]
If Tycho finds a dependency that is an **OSGi bundle with embedded JARs** in its Bundle-Classpath then it **extracts** these embedded JARs and adds these **as additional dependencies** to the classpath.

It seems that sbt-osgi-manager does currently not support this extraction and therefore the Scala compiler is unable to find the classes of these embedded dependencies.

What is the best place to add these functions to sbt-osgi-manager - sbt.osgi.manager.maven.action.Resolve or sbt.osgi.manager.maven.action.ResolveP2?

**Comment by kenwenzel** [comment]
The relevant code in Tycho seems to be this one:

<https://github.com/eclipse/tycho/blob/d256f83e72a67c4d11e466a8980b24877476a30d/tycho-p2/tycho-p2-facade/src/main/java/org/eclipse/tycho/p2/resolver/P2DependencyResolver.java#L436>

**Comment by ezh** [comment]
I don't think that such functionality must be embedded to this plugin.
The reasons is:
1. we have osgiResolve (copy remote dependencies to the local storage) and osgiResolveRemote (add dependencies with original URLs). What is behaviour for nested dependencies that are not downloaded?
2. what is about nested dependencies that you fetch from different sources (from SBT itself, without sbt-osgi-manager as example)?
3. SBT has beautiful plugin API. What is about to create plugin that will scan dependencies after resolution process and unpack inner jar artifacts? This will work always with or without sbt-osgi-manager.

PS You may modify this plugin as you wish. If you want you may create pull request. The only thing is implemented test suite that verify this case.
